#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// Modernize commands
$application->add(new WPModernPlugin\Modernize\CreateServiceCommand());

$application->run();
