#!/usr/bin/env php
<?php

/**
 * Project: WPPluginModernizer
 * File: modernize
 * Author: WPPluginModernizer
 * Date: 3/22/24
 */

require __DIR__ . '/vendor/autoload.php';

use WPPluginModernizer\Modernize\Commands\CustomApplication as Application;
use WPPluginModernizer\Modernize\Commands\RebrandCommand;
use WPPluginModernizer\Modernize\Commands\CreateAPIRoutesCommand;
use WPPluginModernizer\Modernize\Commands\CreateGutenbergBlockCommand;
use WPPluginModernizer\Modernize\Commands\CreateServiceCommand;
use WPPluginModernizer\Modernize\Commands\CreateConsoleCommand;

$application = new Application('WPPluginModernizer', '1.0.1');

// Modernize commands
$application->add(new RebrandCommand());
$application->add(new CreateServiceCommand());
$application->add(new CreateAPIRoutesCommand());
$application->add(new CreateGutenbergBlockCommand());
$application->add(new CreateConsoleCommand());

// Load and register user defined custom commands
$customCommands = require(__DIR__ . '/src/Console/registration.php');
foreach ($customCommands as $customCommandClass) {
    if (class_exists($customCommandClass)) {
        $application->add(new $customCommandClass());
    }
}

$application->run();
