#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use WPModernPlugin\Modernize\CreateServiceCommand;
use WPModernPlugin\Modernize\CreateAPIRoutesCommand;
use WPModernPlugin\Modernize\CreateGutenbergBlockCommand;
use WPModernPlugin\Modernize\ListCommands;

$application = new Application();

// Modernize commands
$application->add(new CreateServiceCommand());
$application->add(new CreateAPIRoutesCommand());
$application->add(new CreateGutenbergBlockCommand());
$application->add(new ListCommands());

// Set the default command to the custom list command
$application->setDefaultCommand((new ListCommands())->getName(), true);


$application->run();
