#!/usr/bin/env php
<?php

// Path to the WPPluginModernizer CLI script
$mainPluginCliPath = '../WPPluginModernizer/wp-plugin-modernizer.php';

// Change the current working directory to the child plugin's directory
chdir(__DIR__);

// Execute the WPPluginModernizer CLI script
require $mainPluginCliPath;
